/*
Localizely API

Testing UploadAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package localizely

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/localizely/localizely-client-go"
)

func Test_localizely_UploadAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UploadAPIAPIService ImportLocalizationFile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		httpRes, err := apiClient.UploadAPIAPI.ImportLocalizationFile(context.Background(), projectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
