/*
Localizely API

Testing BranchAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package localizely

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/localizely/localizely-client-go"
)

func Test_localizely_BranchAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BranchAPIAPIService CreateBranch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var branch string

		httpRes, err := apiClient.BranchAPIAPI.CreateBranch(context.Background(), projectId, branch).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
